# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sample.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='sample.proto',
  package='endpoints.examples.sample',
  syntax='proto3',
  serialized_options=_b('\n$com.google.endpoints.examples.sampleB\013SampleProtoP\001'),
  serialized_pb=_b('\n\x0csample.proto\x12\x19\x65ndpoints.examples.sample\x1a\x1bgoogle/protobuf/empty.proto\"\x1d\n\rSampleMessage\x12\x0c\n\x04name\x18\x01 \x01(\t\"!\n\x11GetMessageRequest\x12\x0c\n\x04name\x18\x01 \x01(\t2s\n\x0b\x45\x63hoService\x12\x64\n\nGetMessage\x12,.endpoints.examples.sample.GetMessageRequest\x1a(.endpoints.examples.sample.SampleMessageB5\n$com.google.endpoints.examples.sampleB\x0bSampleProtoP\x01\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_SAMPLEMESSAGE = _descriptor.Descriptor(
  name='SampleMessage',
  full_name='endpoints.examples.sample.SampleMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='endpoints.examples.sample.SampleMessage.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=101,
)


_GETMESSAGEREQUEST = _descriptor.Descriptor(
  name='GetMessageRequest',
  full_name='endpoints.examples.sample.GetMessageRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='endpoints.examples.sample.GetMessageRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=136,
)

DESCRIPTOR.message_types_by_name['SampleMessage'] = _SAMPLEMESSAGE
DESCRIPTOR.message_types_by_name['GetMessageRequest'] = _GETMESSAGEREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SampleMessage = _reflection.GeneratedProtocolMessageType('SampleMessage', (_message.Message,), dict(
  DESCRIPTOR = _SAMPLEMESSAGE,
  __module__ = 'sample_pb2'
  # @@protoc_insertion_point(class_scope:endpoints.examples.sample.SampleMessage)
  ))
_sym_db.RegisterMessage(SampleMessage)

GetMessageRequest = _reflection.GeneratedProtocolMessageType('GetMessageRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETMESSAGEREQUEST,
  __module__ = 'sample_pb2'
  # @@protoc_insertion_point(class_scope:endpoints.examples.sample.GetMessageRequest)
  ))
_sym_db.RegisterMessage(GetMessageRequest)


DESCRIPTOR._options = None

_ECHOSERVICE = _descriptor.ServiceDescriptor(
  name='EchoService',
  full_name='endpoints.examples.sample.EchoService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=138,
  serialized_end=253,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetMessage',
    full_name='endpoints.examples.sample.EchoService.GetMessage',
    index=0,
    containing_service=None,
    input_type=_GETMESSAGEREQUEST,
    output_type=_SAMPLEMESSAGE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ECHOSERVICE)

DESCRIPTOR.services_by_name['EchoService'] = _ECHOSERVICE

# @@protoc_insertion_point(module_scope)
